name: Monitor-Trial

on:
  schedule:
    # Every 30 minutes
    - cron: "*/30 * * * *"
  workflow_dispatch:  # manual trigger if you ever need it

permissions:
  contents: write  # allow the bot to commit study.json

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run monitor script
        env:
          WEBSITE_URL:  ${{ secrets.WEBSITE_URL }}
          API_URL:  ${{ secrets.API_URL }}
          EMAIL_PASSWORD:  ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_USER:    ${{ secrets.EMAIL_USER }}
          RECIPIENT: ${{ secrets.RECIPIENT }}
        run: |
          python monitor_api.py
        continue-on-error: true

      - name: Commit updated JSON and HTML files (if any)
        run: |
          # Only commit when study.json actually changed
          if git status --porcelain | grep -q "study.json|website.html"; then
            git config user.name  "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add study.json website.html
            git commit -m "Update study.json and website.html ($(date -u +'%Y-%m-%dT%H:%M:%SZ'))"
            git push
          else
            echo "No file changes to commit."
          fi
